// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCommit-1]
	_ = x[TypeCodeScanningAlert-2]
	_ = x[TypeDependabotAlert-3]
	_ = x[TypeIssue-4]
	_ = x[TypePullRequest-5]
	_ = x[TypeRelease-6]
	_ = x[TypeRepositoryRenamed-7]
	_ = x[TypeRepositoryPublic-8]
	_ = x[TypeSecurityAdvisory-9]
	_ = x[TypeSecretScanningAlert-10]
	_ = x[TypeTeam-11]
	_ = x[TypeWorkflow-12]
	_ = x[TypeUnknown-13]
}

const _EventType_name = "TypeCommitTypeCodeScanningAlertTypeDependabotAlertTypeIssueTypePullRequestTypeReleaseTypeRepositoryRenamedTypeRepositoryPublicTypeSecretAdvisoryTypeSecretScanningAlertTypeTeamTypeWorkflowTypeUnknown"

var _EventType_index = [...]uint8{0, 10, 31, 50, 59, 74, 85, 106, 126, 144, 167, 175, 187, 198}

func (i EventType) String() string {
	i -= 1
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
