// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCommit-1]
	_ = x[TypeIssue-2]
	_ = x[TypePullRequest-3]
	_ = x[TypeRelease-4]
	_ = x[TypeRepositoryRenamed-5]
	_ = x[TypeRepositoryPublic-6]
	_ = x[TypeTeam-7]
	_ = x[TypeWorkflow-8]
	_ = x[TypeUnknown-9]
}

const _EventType_name = "TypeCommitTypeIssueTypePullRequestTypeReleaseTypeRepositoryRenamedTypeRepositoryPublicTypeTeamTypeWorkflowTypeUnknown"

var _EventType_index = [...]uint8{0, 10, 19, 34, 45, 66, 86, 94, 106, 117}

func (i EventType) String() string {
	i -= 1
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
