// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package github

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeCommit-1]
	_ = x[TypeDependabotAlert-2]
	_ = x[TypeIssue-3]
	_ = x[TypePullRequest-4]
	_ = x[TypeRelease-5]
	_ = x[TypeRepositoryRenamed-6]
	_ = x[TypeRepositoryPublic-7]
	_ = x[TypeSecretAdvisory-8]
	_ = x[TypeTeam-9]
	_ = x[TypeWorkflow-10]
	_ = x[TypeUnknown-11]
}

const _EventType_name = "TypeCommitTypeDependabotAlertTypeIssueTypePullRequestTypeReleaseTypeRepositoryRenamedTypeRepositoryPublicTypeSecretAdvisoryTypeTeamTypeWorkflowTypeUnknown"

var _EventType_index = [...]uint8{0, 10, 29, 38, 53, 64, 85, 105, 123, 131, 143, 154}

func (i EventType) String() string {
	i -= 1
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
