apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: fetch-teams
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  command:
    - /fetch-teams
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 500m
      memory: 16Mi
  env:
    - name: REPOS_CONFIG_FILE_PATH
      value: /var/run/configmaps/teams.yaml
    - name: GITHUB_ORG
      value: navikt
    - name: GITHUB_BLOCKLIST_REPOS
      value: "vault-iac,aad-iac,nav-api-portal"
    - name: PGURL
      value: "postgresql://$(PGUSER):$(PGPASSWORD)@ghep-pooler.pg-the-g-team:5432/app"
  filesFrom:
    - configmap: ghep-teams
      mountPath: /var/run/configmaps
  envFrom:
    - secret: ghep
  envFrom:
    - secret: app-writer-user.ghep.credentials.postgresql.acid.zalan.do
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
        - ipv4: 3.68.124.95
        - ipv4: 52.29.238.212
        - ipv4: 3.68.175.98
        - ipv4: 18.159.197.225
        - ipv4: 3.68.124.168
        - ipv4: 3.68.170.153
