apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ghep
  namespace: the-g-team
  labels:
    team: the-g-team
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
spec:
  ingresses:
    - https://ghep.nav.no
  replicas:
    max: 2
    min: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 16Mi
  env:
    - name: REPOS_CONFIG_FILE_PATH
      value: /var/run/configmaps/teams.yaml
    - name: GITHUB_ORG
      value: navikt
    - name: GITHUB_BLOCKLIST_REPOS
      value: "vault-iac,aad-iac,nav-api-portal"
    - name: EXTERNAL_CONTRIBUTORS_CHANNEL
      value: github-eksterne-bidragsytere
  filesFrom:
    - configmap: ghep-teams
      mountPath: /var/run/configmaps
  envFrom:
    - secret: ghep
  observability:
    logging:
      destinations:
        - id: loki
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
        - ipv4: 3.68.124.95
        - ipv4: 52.29.238.212
        - ipv4: 3.68.175.98
        - ipv4: 18.159.197.225
        - ipv4: 3.68.124.168
        - ipv4: 3.68.170.153
  postgres:
    cluster:
      majorVersion: "17"
      resources:
        cpu: 100m
        diskSize: 1Gi
        memory: 2G
    database:
      collation: nb_NO
  startup:
    path: /internal/health
    initialDelay: 45
    periodSeconds: 5
  readiness:
    path: /internal/health
  liveness:
    path: /internal/health
  valkey:
    - instance: events
      access: readwrite
