apiVersion: v1
kind: ConfigMap
metadata:
  name: gnep-teams
  namespace: the-g-team
  labels:
    team: the-g-team
  annotations:
    reloader.stakater.com/match: "true"
data:
  teams.yaml: |
    nais:
      commits: "#nais-commits"
      issues: "#nais-issues"
      pulls: "#nais-pull-requests"
      workflows: "#nais-ci"
      releases: "#nais-releases"
      security: "#nais-github-security"
      config:
        ignoreRepositories:
          - "nur"
          - "homebrew-tap"
          - "scoop-bucket"
        silenceDependabot: always
        externalContributorsChannel: "#nais-external-contributors"
        workflows:
          branches:
            - main
            - master

---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: gnep
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  command:
    - /ghep
  ingresses:
    - https://ghep.nav.no/nais
  replicas:
    max: 2
    min: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 16Mi
  env:
    - name: REPOS_CONFIG_FILE_PATH
      value: /var/run/configmaps/teams.yaml
    - name: GITHUB_ORG
      value: nais
    - name: GHEP_SUBSCRIBE_TO_ORG
      value: "true"
    - name: API_BASE_PATH
      value: "/nais"
  filesFrom:
    - configmap: gnep-teams
      mountPath: /var/run/configmaps
  envFrom:
    - secret: gnep
  observability:
    logging:
      destinations:
        - id: loki
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
        - ipv4: 3.68.124.95
        - ipv4: 52.29.238.212
        - ipv4: 3.68.175.98
        - ipv4: 18.159.197.225
        - ipv4: 3.68.124.168
        - ipv4: 3.68.170.153
  postgres:
    cluster:
      majorVersion: "17"
      resources:
        cpu: 100m
        diskSize: 1Gi
        memory: 2G
    database:
      collation: nb_NO
  startup:
    path: /internal/health
    initialDelay: 90
    periodSeconds: 5
  readiness:
    path: /internal/health
  liveness:
    path: /internal/health
  valkey:
    - instance: events
      access: readwrite
