apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: ghep
  namespace: the-g-team
  labels:
    team: the-g-team
spec:
  image: {{ image }}
  ingresses:
    - https://ghep.nav.no
  replicas:
      max: 2
      min: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 16Mi
  env:
    - name: GITHUB_API
      value: https://api.github.com
    - name: REPOS_CONFIG_FILE_PATH
      value: /var/run/configmaps/teams.yaml
    - name: GITHUB_ORG
      value: navikt
    - name: GITHUB_BLOCKLIST_REPOS
      value: "vault-iac,aad-iac"
  filesFrom:
    - configmap: ghep-teams
      mountPath: /var/run/configmaps
  envFrom:
    - secret: ghep
  accessPolicy:
    outbound:
      external:
        - host: api.github.com
        - host: slack.com
  redis:
    - instance: events
      access: readwrite
