apiVersion: v1
kind: ConfigMap
metadata:
  name: ghep-teams
  namespace: the-g-team
  labels:
    team: the-g-team
  annotations:
    reloader.stakater.com/match: "true"
data:
  teams.yaml: |
    nada:
      commits: "#nada-commits"
      issues: "#nada-issues"
      pulls: "#nada-pull-requests"
    flex:
      commits: "#flex-github-feed"
      issues: "#flex-github-feed"
      pulls: "#flex-github-pullrequest-feed"
    tbd:
      commits: "#område-helse-dev"
    dv-a-team:
      commits: "#dv-a-team-commits"
      issues: "#dv-a-team-pull-requests"
      pulls: "#dv-a-team-pull-requests"
    spenn:
      commits: "#spenn-commits"
      issues: "#spenn-pull-requests"
      pulls: "#spenn-pull-requests"
    leesah-quiz:
      commits: "#leesah-game-ci"
      issues: "#leesah-game-ci"
      pulls: "#leesah-game-ci"
