apiVersion: v1
kind: ConfigMap
metadata:
  name: ghep-teams
  namespace: the-g-team
  labels:
    team: the-g-team
  annotations:
    reloader.stakater.com/match: "true"
data:
  teams.yaml: |
    nada:
      commits: "#nada-commits"
      issues: "#nada-issues"
      pulls: "#nada-pull-requests"
      workflows: "#nada-ci"
    aap:
      commits: "#aap-github-workflows"
      releases: "#aap-github-workflows"
      workflows: "#aap-github-workflows"
      config:
        silenceDependabot: "always"
        workflows:
          ignoreBots: true
          branches: ["main"]
    flex:
      commits: "#flex-github-feed"
      issues: "#flex-github-feed"
      pulls: "#flex-github-pullrequest-feed"
      workflows: "#spøkelser"
      config:
        externalContributorsChannel: "#flex-ghep-extern-contrib"
        workflows:
          ignoreBots: false
          branches: ["main"]
    tbd:
      commits: "#område-helse-dev"
      workflows: "#team-bømlo-workflow"
    dv-a-team:
      commits: "#dv-a-team-commits"
      issues: "#dv-a-team-pull-requests"
      pulls: "#dv-a-team-pull-requests"
      workflows: "#dv-a-team-ops"
      security: "#dv-a-team-ops"
    spenn:
      commits: "#spenn-commits"
      issues: "#spenn-pull-requests"
      pulls: "#spenn-pull-requests"
    leesah-quiz:
      commits: "#leesah-game-ci"
      issues: "#leesah-game-ci"
      pulls: "#leesah-game-ci"
    teamsykefravr:
      pulls: "#isyfo-pr"
      workflows: "#syfo-alarm"
      config:
        workflows:
          ignoreBots: true
          branches: ["main", "master"]
    teamsykmelding:
      commits: "tsm-commits"
      workflows: "tsm-broken-actions"
      issues: "tsm-issues"
      config:
        silenceDependabot: "always"
        externalContributorsChannel: "#tsm-extern-contrib"
        workflows:
          ignoreBots: true
          branches: ["main", "master"]
    tsm:
      commits: "tsm-commits"
      workflows: "tsm-broken-actions"
      issues: "tsm-issues"
      config:
        silenceDependabot: "always"
        externalContributorsChannel: "#tsm-extern-contrib"
        workflows:
          ignoreBots: true
          branches: ["main"]
    teamdagpenger:
      commits: "#dp-commits"
      issues: "#dp-issues"
      pulls: "#dp-pull-requests"
      workflows: "#dp-failed-workflows"
    dataseksjonen:
      commits: "#dataseksjonen-github"
      issues: "#dataseksjonen-github"
      pulls: "#dataseksjonen-github"
      workflows: "#dataseksjonen-github"
    fager:
      issues: "#team-fager-bots"
      pulls: "#team-fager-bots"
      workflows: "#team-fager-bots"
    permittering-og-nedbemanning:
      issues: "#team-fager-bots"
      pulls: "#team-fager-bots"
      workflows: "#team-fager-bots"
    arbeidsforhold:
      pulls: "#team-arbeidsforhold-github"
      workflows: "#team-arbeidsforhold-github"
      config:
        ignoreRepositories:
          - "arbeid-og-inntekt"
          - "nav-maskinporten"
        workflows:
          branches: ["main"]
    tilleggsstonader:
      pulls: "#tilleggsstønader-gh-pr"
      config:
        silenceDependabot: "always"
    k9saksbehandling:
      security: "#sif-sikkerhetsvarsel"
      pulls: "#k9saksbehandling-feed"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
        security:
          severityFilter: "high"
    omsorgspenger:
      security: "#sif-sikkerhetsvarsel"
      pulls: "#k9saksbehandling-feed"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
        security:
          severityFilter: "high"
    dusseldorf:
      security: "#sif-sikkerhetsvarsel"
      pulls: "#k9saksbehandling-feed"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
        security:
          severityFilter: "high"
    dolly:
      commits: "#dolly-ghep"
      issues: "#dolly-ghep"
      pulls: "#dolly-ghep"
      workflows: "#dolly-ghep"
    tpts:
      commits: "#tp-github-feed"
      issues: "#tp-github-feed"
      pulls: "#tp-pull-request"
      workflows: "#tp-github-feed"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
    obo:
      issues: "#team-obo-github-events"
      pulls: "#team-obo-pr"
      workflows: "#team-obo-github-events"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
    pensjon-dataprodukt:
      workflows: "#pen-dataprodukt-github"
      commits: "#pen-dataprodukt-github"
      issues: "#pen-dataprodukt-github"
      pulls: "#pen-dataprodukt-github"
    cv:
      issues: "#team-cv-github-events"
      pulls: "#team-cv-github-events"
      workflows: "#team-cv-github-events"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main", "master"]
    hubba-devs:
      workflows: "#team-hubba-alerts"
      config:
        workflows:
          ignoreBots: true
          branches: ["main", "master"]
          repositories: ["pam-stillingsok"]
          workflows: ["Playwright Tests"]
    virksomhetsdatalaget:
      commits: "#virksomhetsdatalaget-gh"
      issues: "#virksomhetsdatalaget-gh"
      pulls: "#virksomhetsdatalaget-gh"
      workflows: "#virksomhetsdatalaget-gh"
      releases: "#virksomhetsdatalaget-gh"
      config:
        workflows:
          branches: ["main", "master"]
    team-nav-no:
      releases: "#team-navno-releases"
      workflows: "#team-navno-failover-prod"
      config:
        silenceDependabot: "always"
        workflows:
          branches: ["main"]
          repos: ["nav-enonicxp-frontend"]
          workflows: ["Deploy til prod-failover"]
    allosaurus:
      issues: "#allosaurus-github"
      pulls: "#allosaurus-github"      
    historisk:
      issues: "#historisk-github"
      pulls: "#historisk-github"
      workflows: "#historisk-github"
      releases: "#historisk-github"
      security: "#historisk-github"
    team-esyfo:
      commits: "#esyfo-github-feed"
      workflows: "#esyfo-github-feed"
      issues: "#esyfo-github-feed"
      pulls: "#esyfo-pull-requests"
      config:
        ignoreRepositories:
          - "arbeidsgiver-notifikasjon-produsenter"
          - "isdialogmelding"
          - "isdialogmote"
          - "isdialogmote-schema"
          - "isnarmesteleder"
          - "isyfomock"
          - "isoppfolgingstilfelle"
          - "nav-ekstern-api-dok"
          - "syfomodiaperson"
        silenceDependabot: "always"
        workflows:
          ignoreBots: true
          branches: ["main", "master"]
    speilvendt:
      commits: "#helseytelser-speilvendt-github"
      issues: "#helseytelser-speilvendt-github"
      pulls: "#helseytelser-speilvendt-github"
      workflows: "#helseytelser-speilvendt-github"
      config:
        silenceDependabot: "always"
        workflows:
          ignoreBots: false
          branches: ["main"]
    yrkesskade:
      workflows: "#yrkesskade-workflows"
      pulls: "#yrkesskade-kodeles"
      releases: "#yrkesskade-releases"
      config:
        silenceDependabot: "always"
        workflows:
          ignoreBots: true
          branches: ["main", "dev"]
    utvikling-admin:
      commits: "utvikling-admin-dev"
      workflows: "utvikling-admin-dev"
      issues: "utvikling-admin-dev"  
      pulls: "utvikling-admin-dev"  
    pdfgen:
      commits: "pdfgen"
      workflows: "pdfgen"
      issues: "pdfgen"  
      pulls: "pdfgen"
    idm:
      security: "#team-idm-security-alerts"
