// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetDigestSentAt = `-- name: GetDigestSentAt :one
SELECT sent_at FROM digest_sent WHERE team_slug = $1
`

func (q *Queries) GetDigestSentAt(ctx context.Context, teamSlug string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, GetDigestSentAt, teamSlug)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const UpsertDigestSent = `-- name: UpsertDigestSent :exec
INSERT INTO digest_sent (team_slug, sent_at) VALUES ($1, $2)
ON CONFLICT (team_slug) DO UPDATE SET sent_at = EXCLUDED.sent_at
`

type UpsertDigestSentParams struct {
	TeamSlug string
	SentAt   pgtype.Timestamptz
}

func (q *Queries) UpsertDigestSent(ctx context.Context, arg UpsertDigestSentParams) error {
	_, err := q.db.Exec(ctx, UpsertDigestSent, arg.TeamSlug, arg.SentAt)
	return err
}
