// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ClaimDigestSlot = `-- name: ClaimDigestSlot :one
INSERT INTO digest_sent (team_slug, sent_at)
VALUES ($1, $2)
ON CONFLICT (team_slug) DO UPDATE
  SET sent_at = EXCLUDED.sent_at
  WHERE digest_sent.sent_at < $3
RETURNING sent_at
`

type ClaimDigestSlotParams struct {
	TeamSlug    string
	SentAt      pgtype.Timestamptz
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) ClaimDigestSlot(ctx context.Context, arg ClaimDigestSlotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ClaimDigestSlot, arg.TeamSlug, arg.SentAt, arg.ScheduledAt)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}
