// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gensql

type Email struct {
	Login string
	Email string
}

type Repository struct {
	ID   int32
	Name string
}

type Team struct {
	Slug string
}

type TeamMember struct {
	TeamSlug  string
	UserLogin string
}

type TeamRepository struct {
	TeamSlug     string
	RepositoryID int32
}

type User struct {
	Login string
}
