// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: personal_digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetPersonalDigestSentAt = `-- name: GetPersonalDigestSentAt :one
SELECT sent_at FROM personal_digest_sent WHERE login = $1
`

func (q *Queries) GetPersonalDigestSentAt(ctx context.Context, login string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, GetPersonalDigestSentAt, login)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const GetUserCommitsSince = `-- name: GetUserCommitsSince :many
SELECT repo, commit_count
FROM user_commit_counts
WHERE login = $1 AND last_pushed_at > $2
ORDER BY commit_count DESC
`

type GetUserCommitsSinceParams struct {
	Login        string
	LastPushedAt pgtype.Timestamptz
}

type GetUserCommitsSinceRow struct {
	Repo        string
	CommitCount int32
}

func (q *Queries) GetUserCommitsSince(ctx context.Context, arg GetUserCommitsSinceParams) ([]GetUserCommitsSinceRow, error) {
	rows, err := q.db.Query(ctx, GetUserCommitsSince, arg.Login, arg.LastPushedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCommitsSinceRow
	for rows.Next() {
		var i GetUserCommitsSinceRow
		if err := rows.Scan(&i.Repo, &i.CommitCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUsersWithCommitsSince = `-- name: ListUsersWithCommitsSince :many
SELECT DISTINCT login FROM user_commit_counts WHERE last_pushed_at > $1
`

func (q *Queries) ListUsersWithCommitsSince(ctx context.Context, lastPushedAt pgtype.Timestamptz) ([]string, error) {
	rows, err := q.db.Query(ctx, ListUsersWithCommitsSince, lastPushedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login string
		if err := rows.Scan(&login); err != nil {
			return nil, err
		}
		items = append(items, login)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertPersonalDigestSent = `-- name: UpsertPersonalDigestSent :exec
INSERT INTO personal_digest_sent (login, sent_at) VALUES ($1, $2)
ON CONFLICT (login) DO UPDATE SET sent_at = EXCLUDED.sent_at
`

type UpsertPersonalDigestSentParams struct {
	Login  string
	SentAt pgtype.Timestamptz
}

func (q *Queries) UpsertPersonalDigestSent(ctx context.Context, arg UpsertPersonalDigestSentParams) error {
	_, err := q.db.Exec(ctx, UpsertPersonalDigestSent, arg.Login, arg.SentAt)
	return err
}

const UpsertUserCommitCount = `-- name: UpsertUserCommitCount :exec
INSERT INTO user_commit_counts (login, repo, commit_count, last_pushed_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (login, repo)
DO UPDATE SET
    commit_count   = user_commit_counts.commit_count + EXCLUDED.commit_count,
    last_pushed_at = EXCLUDED.last_pushed_at
`

type UpsertUserCommitCountParams struct {
	Login        string
	Repo         string
	CommitCount  int32
	LastPushedAt pgtype.Timestamptz
}

func (q *Queries) UpsertUserCommitCount(ctx context.Context, arg UpsertUserCommitCountParams) error {
	_, err := q.db.Exec(ctx, UpsertUserCommitCount,
		arg.Login,
		arg.Repo,
		arg.CommitCount,
		arg.LastPushedAt,
	)
	return err
}
