// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetSecurityDigestSentAt = `-- name: GetSecurityDigestSentAt :one
SELECT sent_at FROM security_digest_sent WHERE team_slug = $1
`

func (q *Queries) GetSecurityDigestSentAt(ctx context.Context, teamSlug string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, GetSecurityDigestSentAt, teamSlug)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}

const UpsertSecurityDigestSent = `-- name: UpsertSecurityDigestSent :exec
INSERT INTO security_digest_sent (team_slug, sent_at) VALUES ($1, $2)
ON CONFLICT (team_slug) DO UPDATE SET sent_at = EXCLUDED.sent_at
`

type UpsertSecurityDigestSentParams struct {
	TeamSlug string
	SentAt   pgtype.Timestamptz
}

func (q *Queries) UpsertSecurityDigestSent(ctx context.Context, arg UpsertSecurityDigestSentParams) error {
	_, err := q.db.Exec(ctx, UpsertSecurityDigestSent, arg.TeamSlug, arg.SentAt)
	return err
}
