// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ClaimSecurityDigestSlot = `-- name: ClaimSecurityDigestSlot :one
INSERT INTO security_digest_sent (team_slug, sent_at)
VALUES ($1, $2)
ON CONFLICT (team_slug) DO UPDATE
  SET sent_at = EXCLUDED.sent_at
  WHERE security_digest_sent.sent_at < $3
RETURNING sent_at
`

type ClaimSecurityDigestSlotParams struct {
	TeamSlug    string
	SentAt      pgtype.Timestamptz
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) ClaimSecurityDigestSlot(ctx context.Context, arg ClaimSecurityDigestSlotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ClaimSecurityDigestSlot, arg.TeamSlug, arg.SentAt, arg.ScheduledAt)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}
