// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: slack.sql

package gensql

import (
	"context"
)

const createSlackMessage = `-- name: CreateSlackMessage :exec
INSERT INTO slack_messages (team_slug, event_id, thread_ts, channel, payload) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (team_slug, event_id) DO UPDATE
SET thread_ts = EXCLUDED.thread_ts,
    channel = EXCLUDED.channel,
    payload = EXCLUDED.payload
`

type CreateSlackMessageParams struct {
	TeamSlug string
	EventID  string
	ThreadTs string
	Channel  string
	Payload  []byte
}

func (q *Queries) CreateSlackMessage(ctx context.Context, arg CreateSlackMessageParams) error {
	_, err := q.db.Exec(ctx, createSlackMessage,
		arg.TeamSlug,
		arg.EventID,
		arg.ThreadTs,
		arg.Channel,
		arg.Payload,
	)
	return err
}

const getSlackMessage = `-- name: GetSlackMessage :one
SELECT thread_ts, channel, payload
FROM slack_messages
WHERE team_slug = $1 AND event_id = $2
`

type GetSlackMessageParams struct {
	TeamSlug string
	EventID  string
}

type GetSlackMessageRow struct {
	ThreadTs string
	Channel  string
	Payload  []byte
}

func (q *Queries) GetSlackMessage(ctx context.Context, arg GetSlackMessageParams) (GetSlackMessageRow, error) {
	row := q.db.QueryRow(ctx, getSlackMessage, arg.TeamSlug, arg.EventID)
	var i GetSlackMessageRow
	err := row.Scan(&i.ThreadTs, &i.Channel, &i.Payload)
	return i, err
}

const updateSlackMessage = `-- name: UpdateSlackMessage :exec
UPDATE slack_messages
SET payload = $3
WHERE team_slug = $1 AND event_id = $2
`

type UpdateSlackMessageParams struct {
	TeamSlug string
	EventID  string
	Payload  []byte
}

func (q *Queries) UpdateSlackMessage(ctx context.Context, arg UpdateSlackMessageParams) error {
	_, err := q.db.Exec(ctx, updateSlackMessage, arg.TeamSlug, arg.EventID, arg.Payload)
	return err
}
