// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_digest.sql

package gensql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ClaimTeamDigestSlot = `-- name: ClaimTeamDigestSlot :one
INSERT INTO team_digest_sent (type, team_slug, sent_at)
VALUES ($1, $2, $3)
ON CONFLICT (type, team_slug) DO UPDATE
  SET sent_at = EXCLUDED.sent_at
  WHERE team_digest_sent.sent_at < $4
RETURNING sent_at
`

type ClaimTeamDigestSlotParams struct {
	Type        string
	TeamSlug    string
	SentAt      pgtype.Timestamptz
	ScheduledAt pgtype.Timestamptz
}

func (q *Queries) ClaimTeamDigestSlot(ctx context.Context, arg ClaimTeamDigestSlotParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, ClaimTeamDigestSlot,
		arg.Type,
		arg.TeamSlug,
		arg.SentAt,
		arg.ScheduledAt,
	)
	var sent_at pgtype.Timestamptz
	err := row.Scan(&sent_at)
	return sent_at, err
}
