// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package gensql

import (
	"context"
)

const createEmail = `-- name: CreateEmail :exec
INSERT INTO emails (login, email) VALUES ($1, $2)
ON CONFLICT (login, email) DO NOTHING
`

type CreateEmailParams struct {
	Login string
	Email string
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) error {
	_, err := q.db.Exec(ctx, createEmail, arg.Login, arg.Email)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (login) VALUES ($1)
ON CONFLICT (login) DO NOTHING
`

func (q *Queries) CreateUser(ctx context.Context, login string) error {
	_, err := q.db.Exec(ctx, createUser, login)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE login = $1
`

func (q *Queries) DeleteUser(ctx context.Context, login string) error {
	_, err := q.db.Exec(ctx, deleteUser, login)
	return err
}

const getUser = `-- name: GetUser :one
SELECT login FROM users WHERE login = $1
`

func (q *Queries) GetUser(ctx context.Context, login string) (string, error) {
	row := q.db.QueryRow(ctx, getUser, login)
	err := row.Scan(&login)
	return login, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT e.login
FROM emails e
WHERE e.email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var login string
	err := row.Scan(&login)
	return login, err
}
