name: Lint teams

on:
  push:
    branches-ignore:
      - main
    paths:
      - ".nais/teams.yaml"
      - ".github/workflows/linting.yaml"

jobs:
  lint-teams:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7.0.1
      - name: Lint the yaml
        run: yamllint -c .yamllint.yaml .nais/teams.yaml
      - name: Validate it
        run: go run cmd/validate/validate.go .nais/teams.yaml
