name: Deploy teams config

on:
  push:
    branches:
      - main
    paths:
      - ".nais/teams.yaml"
      - ".github/workflows/update_teams.yaml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
      - name: Generate k8s resource for teams.yaml
        run: |
          yq '
          .data["teams.yaml"] = load_str(strenv(TEAMS_FILE))
          ' .nais/teams-resource.yaml > .nais/teams_for_deploy.yaml
        env:
          TEAMS_FILE: .nais/teams.yaml
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/teams_for_deploy.yaml
